setup:
  method: PE
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: null
public_data:
  name: null
sensitive_data:
  name: cifar10
  num_channels: 3
  resolution: 32
  n_classes: 10
  train_path: dataset/cifar10/train_32.zip
  test_path: dataset/cifar10/test_32.zip
  fid_stats: dataset/cifar10/fid_stats_32.npz
model:
  api: sd
  feature_extractor: inception_v3
  api_params:
    ckpt: null
    denoiser_name: edm
    denoiser_network: song
    ema_rate: 0.999
    batch_size: 2000
    network:
      image_size: 32
      num_in_channels: 3
      num_out_channels: 3
      label_dim: 1000
      attn_resolutions:
      - 16
      ch_mult:
      - 2
      - 4
    sampler:
      type: ddim
      stochastic: false
      num_steps: 100
      tmin: 0.002
      tmax: 80.0
      rho: 7.0
      guid_scale: 0.0
  private_num_classes: 10
  public_num_classes: 1000
  ckpt: null
pretrain:
  log_dir: null
  cond: true
train:
  batch_size: 2000
  feature_extractor_batch_size: 500
  private_image_size: 32
  private_num_classes: 10
  num_samples_schedule:
  - 60000
  - 60000
  - 60000
  - 60000
  - 60000
  - 60000
  variation_degree_schedule:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  initial_prompt: null
  image_size: 64x64
  lookahead_degree: 8
  num_nearest_neighbor: 1
  nn_mode: L2
  count_threshold: 15.0
  log_dir: null
  tmp_folder: dataset/cifar10/pe_tmp
  dp:
    epsilon: 1.0
    delta: 1e-5
    privacy_history: null
  n_splits: 1
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
  num_channels: 3
  resolution: 32
eval:
  batch_size: 1000
  mode: val
