setup:
  method: PE
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/pe/mnist_28_eps1.0
public_data:
  name: null
  train_path: dataset/dpimagebench/imagenet_128
sensitive_data:
  name: celeba_male_32
  num_channels: 3
  resolution: 128
  n_classes: 2
  train_path: dataset/celeba/train_128_Male.zip
  test_path: dataset/celeba/test_128_Male.zip
  fid_stats: dataset/celeba/fid_stats_128.npz
model:
  api: guided_diffusion
  feature_extractor: inception_v3
  api_params:
    model_image_size: 128
    num_channels: 256
    num_heads: 4
    num_res_blocks: 2
    resblock_updown: true
    learn_sigma: true
    class_cond: true
    diffusion_steps: 1000
    noise_schedule: linear
    use_scale_shift_norm: true
    rescale_learned_sigmas: false
    rescale_timesteps: false
    use_ddim: true
    attention_resolutions: 32,16,8
    timestep_respacing: 50
    batch_size: 500
    model_path: models/pretrained_models/128x128_diffusion.pt
  private_num_classes: 2
  public_num_classes: 1000
  ckpt: null
pretrain:
  log_dir: null
  cond: true
train:
  batch_size: 500
  feature_extractor_batch_size: 500
  private_image_size: 128
  private_num_classes: 2
  num_samples_schedule:
  - 60000
  - 60000
  - 60000
  - 60000
  - 60000
  - 60000
  variation_degree_schedule:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  initial_prompt: null
  image_size: 128x128
  lookahead_degree: 8
  num_nearest_neighbor: 1
  nn_mode: L2
  count_threshold: 2.0
  log_dir: null
  tmp_folder: dataset/celeba/pe_tmp
  dp:
    epsilon: 10.0
    delta: 1e-5
  n_splits: 1
gen:
  data_num: 1000
  batch_size: 1000
  log_dir: null
  num_channels: 3
  resolution: 128
eval:
  batch_size: 1000
  mode: val
